### ISSUE TITLE
killed jobs (signaled by ctrl-C) are shown in joblist

### ISSUE THREAD

**Issue by omergafla** [omergafla/smash#19]

**Comment by chenkastner** [comment]
:O

**Comment by omergafla** [comment]
added this condition:

returned_pid = waitpid(it->second->process_id, &status, WCONTINUED | WUNTRACED | WNOHANG);
    is_exited = WIFEXITED(status);
    is_stopped = WIFSTOPPED(status);
    is_continued = WIFCONTINUED(status);
    if (is_exited || **returned_pid == -1**)

explanation:

once a process is dead (R.I.P) - the waitpid function won't be able to wait for him (because there is no such PID), therefore it returns a -1 value, if so, we should state the process is finished.
