### ISSUE TITLE
might be a bug:

### ISSUE THREAD

**Issue by omergafla** [omergafla/smash#20]
example:

process 30& start running in BG.
I send it to FG and then its time in jobs list seemed to be restart, I'm not sure, maybe it's too late.

**Comment by chenkastner** [comment]
![image](https://user-images.githubusercontent.com/64319113/99882074-751ac480-2c26-11eb-8fdc-33d715af7d37.png)

**Comment by omergafla** [comment]
WONDEFRULLLLLLLLLLL
